name: DATA


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
  workflow_dispatch:


jobs:
  job1: 
    name: primeiro_job
    runs-on: ubuntu-latest
    
    
    steps:
    - name: primeiro
      run: date
      
