
name: exercicio-2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VAR: 'TESTE VARIAVEL - WORKFLOW'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
      JOB_JOB: 'CRIANDO VARIAVEL DO JOB'
     
     
    steps:
   
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: aplicativo-FLAVIO-BERNARDONI-BUENO
        path: .
        if-no-files-found: error
        retention-days: 3
 
