name: DATA


on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
  workflow_dispatch:


jobs:
  job1: 
    name: primeiro_job
    runs-on: ubuntu-latest
       
    steps:
    - name: primeiro
      run: date
    
  
  job2: 
    name: segundo_job
    runs-on: windows-latest
    
    
    steps:
    - name: segundo
      run: date
      
      
  job3: 
    name: terceiro_job
    runs-on: macos-latest
    
    
    steps:
    - name: terceiro
      run: date
      
  
